/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import com.sun.org.apache.xerces.internal.impl.dv.xs.DateDV;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sun.util.calendar.BaseCalendar;
import java.util.Calendar;
import java.util.Date;


public class form_pengembalian extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet RsPengembalian;
private ResultSet RsRental;
private ResultSet RsMobil;
private ResultSet RsStatus;
private ResultSet RsPenyewa;
private ResultSet RsM;
private String sql="";

private String tanggal1,tanggal2,idpengembalian,idrental,namapenyewa,namamobil,bm,status,idmobil,idpenyewa;
private int harga,hari,total;
    /**
     * Creates new form frmPengembalian
     */
    public form_pengembalian() {
        initComponents();
        KoneksiPengembalian();
        TampilData(sql);
        tanggalrental.setEnabled(false);
    }

    private void KoneksiPengembalian(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_rental_mobil", "root","");
            System.out.println("Koneksi Berhasil");
        } catch (Exception e) {
            System.out.println("Koneksi Gagal \n"+e);
        }
    }
    private void TampilData (String sql){
        DefaultTableModel datalist = new DefaultTableModel();
        datalist.addColumn("No");
        datalist.addColumn("ID PENGEMBALIAN");
        datalist.addColumn("ID RENTAL");
        datalist.addColumn("ID PENYEWA");
        datalist.addColumn("ID MOBIL");
        datalist.addColumn("TANGGAL KEMBALI");
        datalist.addColumn("LAMA");
        datalist.addColumn("TOTAL BAYAR");
        try {
            int i = 1;
            st=con.createStatement();
            RsPengembalian=st.executeQuery("SELECT * FROM tb_pengembalian") ;
            while (RsPengembalian.next())
                datalist.addRow(new Object[]{
                    (""+i++),
                    RsPengembalian.getString(1), RsPengembalian.getString(2), 
                    RsPengembalian.getString(3), RsPengembalian.getString(4), 
                    RsPengembalian.getString(6), RsPengembalian.getString(7),
                    RsPengembalian.getString(8)
                });
            tabel.setModel(datalist);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                "Gagal Tampil \n"+e.getMessage());
        }
    }
    private void bersih(){
        Txt_harga.setText("");
        Txt_id_mobil.setText("");
        Txt_id_pengembalian.setText("");
        Txt_id_penyewa.setText("");
        Txt_lama.setText("");
        Txt_nama_mobil.setText("");
        Txt_nama_penyewa.setText("");
        Txt_status.setText("");
        Txt_total.setText("");
        Cmb_status.setSelectedItem("PILIH");
        Cmb_id_rental.setSelectedItem("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Txt_harga = new javax.swing.JTextField();
        tanggalrental = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        tanggalkembali = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        Txt_lama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Txt_total = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Txt_status = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Txt_id_pengembalian = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Cmb_status = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        Cmb_id_rental = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Txt_id_penyewa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_id_mobil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_nama_penyewa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Txt_nama_mobil = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transaksi Pengembalian");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PENGEMBALIAN", "ID RENTAL", "ID PENYEWA", "ID MOBIL", "TANGGAL KEMBALI", "LAMA", "TOTAL BAYAR"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Tambah Transaksi"));

        jLabel9.setText("Harga Sewa");

        jLabel10.setText("Tanggal Rental");

        Txt_harga.setEnabled(false);

        tanggalrental.setEnabled(false);
        tanggalrental.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalrentalPropertyChange(evt);
            }
        });

        jLabel11.setText("Tanggal Kembali");

        tanggalkembali.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalkembaliPropertyChange(evt);
            }
        });

        jLabel12.setText("Lama Sewa");

        Txt_lama.setEnabled(false);

        jLabel13.setText("Total Bayar");

        Txt_total.setEnabled(false);

        jLabel14.setText("Status");

        Txt_status.setEnabled(false);

        jLabel1.setText("Id Pengembalian");

        Txt_id_pengembalian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_id_pengembalianKeyPressed(evt);
            }
        });

        jLabel2.setText("Pilihan Kembali");

        Cmb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "KEMBALI" }));
        Cmb_status.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_statusItemStateChanged(evt);
            }
        });
        Cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_statusActionPerformed(evt);
            }
        });

        jLabel3.setText("Id Rental");

        Cmb_id_rental.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Cmb_id_rentalItemStateChanged(evt);
            }
        });
        Cmb_id_rental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cmb_id_rentalActionPerformed(evt);
            }
        });

        jLabel4.setText("Id Penyewa");

        Txt_id_penyewa.setEnabled(false);

        jLabel5.setText("Id Mobil");

        Txt_id_mobil.setEnabled(false);

        jLabel6.setText("Nama Penyewa");

        Txt_nama_penyewa.setEnabled(false);

        jLabel7.setText("Nama Mobil");

        Txt_nama_mobil.setEnabled(false);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Batal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Keluar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_nama_penyewa)
                    .addComponent(Txt_id_mobil, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Txt_id_penyewa)
                    .addComponent(Cmb_id_rental, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Txt_nama_mobil)
                    .addComponent(Cmb_status, javax.swing.GroupLayout.Alignment.TRAILING, 0, 235, Short.MAX_VALUE)
                    .addComponent(Txt_id_pengembalian))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Txt_total, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_lama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalkembali, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(tanggalrental, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Txt_harga, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_status))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_id_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(Cmb_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(tanggalrental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(tanggalkembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Cmb_id_rental, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton2)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_id_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(Txt_lama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_id_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)
                            .addComponent(Txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Txt_nama_penyewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(Txt_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Txt_nama_mobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu3.setText("Master");

        jMenuItem1.setText("Mobil");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem2.setText("Penyewa");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Transaksi");

        jMenuItem3.setText("Sewa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Kembali");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tanggalrentalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalrentalPropertyChange
        // TODO add your handling code here:
        if(tanggalrental.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
              tanggal1=format.format(tanggalrental.getDate());
        }
    }//GEN-LAST:event_tanggalrentalPropertyChange

    private void tanggalkembaliPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalkembaliPropertyChange
        // TODO add your handling code here:
        if(tanggalkembali.getDate()!=null){
            SimpleDateFormat format=new SimpleDateFormat("yyyy-MM-dd");
              tanggal2=format.format(tanggalkembali.getDate());
        }
        
        
        try {
         DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
         Date pinjam = tanggalrental.getDate();
         Date kembali = tanggalkembali.getDate();
            long pinjam1 = pinjam.getTime();
            long kembali1 = kembali.getTime();
            long diff = kembali1-pinjam1;
            long lama = diff/(24*60*60*1000);
            Txt_lama.setText(Long.toString(lama));
        harga=Integer.parseInt(Txt_harga.getText());
        hari=Integer.parseInt(Txt_lama.getText());
        total=harga*hari;
        Txt_total.setText(String.valueOf(total));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tanggalkembaliPropertyChange

    private void Cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_statusActionPerformed
        // TODO add your handling code here:
        if (Cmb_status.getSelectedItem()=="KEMBALI"){
        Cmb_id_rental.removeAllItems();
        Cmb_id_rental.addItem("PILIH");
        try {
            status=String.valueOf(Cmb_status.getSelectedItem());
            status = "SEWA";
            String Sql = "select * from tb_rental where status = '"+ status +"'";
            Statement st = con.createStatement();
            RsRental=st.executeQuery(Sql);
            while (RsRental.next()){
                String AliasID = RsRental.getString("id_rental");
                Cmb_id_rental.addItem(AliasID);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    "Gagal Menampilkan id rental \n"
            +e.getMessage());
        }
        }
    }//GEN-LAST:event_Cmb_statusActionPerformed

    private void Cmb_statusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_statusItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_Cmb_statusItemStateChanged

    private void Cmb_id_rentalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Cmb_id_rentalItemStateChanged
        // TODO add your handling code here:
        try {
            sql="select * from tb_rental where "
                    + "id_rental='"+ Cmb_id_rental.getSelectedItem() +"'";
            st=con.createStatement();
            RsRental=st.executeQuery(sql);
            while (RsRental.next()){
                Txt_id_mobil.setText(RsRental.getString("id_mobil"));
                Txt_id_penyewa.setText(RsRental.getString("id_penyewa"));
                Txt_nama_penyewa.setText(RsRental.getString("nama_penyewa"));
                tanggalrental.setDate((RsRental.getDate(7)));
                Txt_nama_mobil.setText(RsRental.getString("nama_mobil"));
                Txt_harga.setText(RsRental.getString("harga_sewa"));
                Txt_status.setText(RsRental.getString("status"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Cmb_id_rentalItemStateChanged

    private void Txt_id_pengembalianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_id_pengembalianKeyPressed
        // TODO add your handling code here:
        idpengembalian=Txt_id_pengembalian.getText();
        int tekanenter=evt.getKeyCode();
        if (tekanenter==10){
        try {
            String Sql = "select * from tb_rental";
            Statement st = con.createStatement();
            RsRental=st.executeQuery(Sql);
            while (RsRental.next()){
                String Aliaskd = RsRental.getString("id_rental");
                Cmb_id_rental.addItem(Aliaskd);
                Cmb_status.setEnabled(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    "Gagal Menampilkan id mobil \n"
            +e.getMessage());
        }
            try {
                sql="select * from tb_pengembalian "
                        + "where id_pengembalian='"+ idpengembalian +"'";
                st=con.createStatement();
                RsPengembalian=st.executeQuery(sql);
                while (RsPengembalian.next()){
                    Cmb_id_rental.setSelectedItem(RsPengembalian.getString("id_rental"));
                    Txt_id_mobil.setText(RsPengembalian.getString("id_mobil"));
                    tanggalrental.setDate((RsPengembalian.getDate("tgl_rental")));
                    tanggalkembali.setDate((RsPengembalian.getDate("tgl_kembali")));
                    Txt_lama.setText(RsPengembalian.getString("lama"));
                    Txt_total.setText(RsPengembalian.getString("total_bayar"));
                    Txt_status.setText(RsPengembalian.getString("status"));
                    JOptionPane.showMessageDialog(null, "Data Ditemukan");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gak Ketemu \n"
                    +e.getMessage());
            }
        }
    }//GEN-LAST:event_Txt_id_pengembalianKeyPressed

    private void Cmb_id_rentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cmb_id_rentalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cmb_id_rentalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        idrental=Cmb_id_rental.getItemAt(Cmb_id_rental.getSelectedIndex()).toString();
        idmobil=String.valueOf(Txt_id_mobil.getText());
        idpenyewa=String.valueOf(Txt_id_penyewa.getText());
        namapenyewa=String.valueOf(Txt_nama_penyewa.getText());
        namamobil=String.valueOf(Txt_nama_mobil.getText());
        harga=Integer.parseInt(Txt_harga.getText());
        hari=Integer.parseInt(Txt_lama.getText());
        total=Integer.parseInt(Txt_total.getText());
        status=Cmb_status.getItemAt(Cmb_status.getSelectedIndex()).toString();
        if (Cmb_status.getSelectedItem().equals("SELESAI")){
            JOptionPane.showMessageDialog(null, "MAAF MOBIL SUDAH DIKEMBALIKAN");
            bersih();
        }
        else if (Txt_id_pengembalian.getText().equals("")){
        JOptionPane.showMessageDialog(null, "MAAF ID PENGEMBALIAN MASIH KOSONG");
        
        }
        else {
        try {
            sql="INSERT INTO tb_pengembalian(id_pengembalian, id_rental,id_mobil,id_penyewa, "
                    + "tgl_rental, tgl_kembali,lama,total_bayar,status)VALUE"
                    + "('"+ idpengembalian +"','"+ idrental +"','"+ idmobil +"','"+ idpenyewa +"',"
                    + "'"+ tanggal1 +"','"+ tanggal2 +"','"+ hari +"','"+ total +"','"+ status +"')";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, 
                    "Data Berhasil Disimpan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    "Data Gagal Disimpan \n"+e.getMessage());
        
        }
        
        try {
            String sql="select * from tb_mobil";
            Statement st = con.createStatement();
            RsMobil=st.executeQuery(sql);
            status = "READY";
            sql="update tb_mobil set status = '"+ status +"' where id_mobil = '"+ idmobil +"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf error"+e.getMessage());
        }
        try {
            status = "SELESAI";
            sql="update tb_rental set status = '"+ status +"' where id_rental = '"+ idrental +"'";
            st=con.createStatement();
            st.execute(sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "maaf error"+e.getMessage());
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        idrental=Cmb_id_rental.getItemAt(Cmb_id_rental.getSelectedIndex()).toString();
        idmobil=String.valueOf(Txt_id_mobil.getText());
        idpenyewa=String.valueOf(Txt_id_penyewa.getText());
        namapenyewa=String.valueOf(Txt_nama_penyewa.getText());
        namamobil=String.valueOf(Txt_nama_mobil.getText());
        harga=Integer.parseInt(Txt_harga.getText());
        hari=Integer.parseInt(Txt_lama.getText());
        total=Integer.parseInt(Txt_total.getText());
        status=Cmb_status.getItemAt(Cmb_status.getSelectedIndex()).toString();
        try {
            sql="update tb_pengembalian set tgl_kembali='"+ tanggal2 +"',lama='"+ hari +"',total_bayar='"+ total +"',status='"+ status +"' "
                    + "where id_pengembalian='"+ idpengembalian +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, 
                    "Data Berhasil Di ubah");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, 
                    "Data Gagal Di Ubah \n"+e.getMessage());
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        idpengembalian=String.valueOf(Txt_id_pengembalian.getText());
        try {
            sql="delete from tb_pengembalian where id_pengembalian = '"+ idpengembalian +"'";
            st=con.createStatement();
            st.execute(sql);
            bersih();
            TampilData(sql);
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dihapus"+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String ObjButtons[] = {"Yes","No"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda Yakin Ingin keluar ?","Message",JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,ObjButtons,ObjButtons[1]);
        if(pilihan == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        form_mobil m=new form_mobil();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        form_penyewa m=new form_penyewa();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        form_rental m=new form_rental();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        form_pengembalian m=new form_pengembalian();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cmb_id_rental;
    private javax.swing.JComboBox<String> Cmb_status;
    private javax.swing.JTextField Txt_harga;
    private javax.swing.JTextField Txt_id_mobil;
    private javax.swing.JTextField Txt_id_pengembalian;
    private javax.swing.JTextField Txt_id_penyewa;
    private javax.swing.JTextField Txt_lama;
    private javax.swing.JTextField Txt_nama_mobil;
    private javax.swing.JTextField Txt_nama_penyewa;
    private javax.swing.JTextField Txt_status;
    private javax.swing.JTextField Txt_total;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private com.toedter.calendar.JDateChooser tanggalkembali;
    private com.toedter.calendar.JDateChooser tanggalrental;
    // End of variables declaration//GEN-END:variables
}
